import React, { useEffect, VoidFunctionComponent } from 'react';
import { Box, Button } from '@mui/material';
import Head from 'next/head';
import AddCircleIcon from '@mui/icons-material/AddCircle';
import { useState } from 'react';
import DashboardLayout from 'layouts/DashboardLayout';
import Container from '@mui/material/Container';
import TransactionsTable from './components/TransactionsTable';
import { ITransaction } from 'interfaces/income.interface';
import { transactionService } from 'services';
import CreateTransactionModal from './components/CreateTransactionModal';

const HomeTemplate: VoidFunctionComponent = () => {
  const [open, setOpen] = useState(false);

  const [transactions, setTransactions] = useState<ITransaction[]>([]);

  useEffect(() => {
    const fetch = async () => {
      const transactions = await transactionService.getTransactions();
      setTransactions(transactions);
    };
    fetch();
  }, []);

  const handleSave = (data) => {
    console.log('data', data);
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DashboardLayout>
        <Container maxWidth="xl">
          <div>
            <Box
              aria-label="toolbar"
              sx={{ display: 'flex', marginTop: '20px', marginBottom: '20px' }}
            >
              <Box sx={{ flex: '1 1 auto' }}></Box>
              <Button
                variant="contained"
                endIcon={<AddCircleIcon />}
                onClick={() => setOpen(true)}
              >
                Crea nuevo registro
              </Button>
            </Box>
            <TransactionsTable transactions={transactions} />
          </div>
          <CreateTransactionModal
            open={open}
            onClose={() => setOpen(false)}
            onSave={handleSave}
          />
        </Container>
      </DashboardLayout>
    </>
  );
};

export default HomeTemplate;
