import { Box } from '@mui/material';
import DashboardLayout from 'layouts/DashboardLayout';
import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const IncomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Income</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <Box>IncomePage</Box>
      </DashboardLayout>
    </>
  );
};

export default IncomePage;
