import { Box } from '@mui/material';
import DashboardSkeleton from 'components/DashboardSkeleton';
import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const IncomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Income</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardSkeleton>
        <Box>IncomePage</Box>
      </DashboardSkeleton>
    </>
  );
};

export default IncomePage;
